version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ancientbible
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
